name: CI

# Déclenchement sur push et pull request sur toutes les branches
on:
  push: {}
  pull_request: {}

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      # 1/ Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2/ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3/ Install dependencies + pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      # 4/ Run tests
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

      # 5/ Build Docker image
      - name: Build Docker image
        run: docker build -t weather-api:ci .
