name: CI

on:
  push: {}
  pull_request: {}

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      # 1/ Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2/ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3/ Install dependencies + pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt pytest

      # 4/ Ugly fix 
      - name: Create package alias
        run: ln -s $PWD flask_weather_api

      # 5/ Run tests
      - name: Run tests
        run: export PYTHONPATH=$PWD; pytest --maxfail=1 --disable-warnings -q

      # 6/ Build Docker image
      - name: Build Docker image
        run: docker build -t weather-api:ci .
